contact/urls.py
"""
This .py file defines the URL configuration for the 'contact' app in my Django project.

The `urlpatterns` list is a collection of URL patterns associated with view functions or classes.
In this case, there is a single URL pattern defined for the 'contact' app. It maps the root URL
(path '') to the `contact_view` function from the `views` module. The name of this URL pattern
is set as 'contact'.

The `app_name` variable defines the namespace for the 'contact' app. It helps in resolving URL
names when multiple apps have URL patterns with the same name.

"""
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'contact'
urlpatterns = [
    path('', views.contact_view, name='contact'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('tourdates/', views.tourdates, name='tourdates'),
]

illusion/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import detail

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('admin/', admin.site.urls),
    path('tourdates/', include('tourdates.urls', namespace ='tourdates')),
    path('homepage/', include('homepage.urls', namespace='homepage')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('polls/<int:question_id>/', detail, name='detail'),
    path('user_auth/', include(("django.contrib.auth.urls", 'registration'))),
    path('user_path/', include("user_auth.urls")),

]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='details'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
"""

This .py file contains Django models for a simple question and choice system.

The Question model represents a question with a question text and the date it was published.
Its is defined as a subclass of the models.Model class
The __str__ method is overridden to return a string representation of the question
text.

The Choice model represents a choice with a choice text, This is also defined as a subclass of models.Model.
The question field is a foreign key to the Questions model establishing a one-to-many relationship
between questions and choices.The __str__ method is overridden to return a string representation of the choice
text.

These models define the structure and behavior of the data stored in the applications database.
They allow the application to create, retrieve, update, and delete question and choice objects in the database.

"""
from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
"""

This .py file contains Django view functions for a polling application.
The views handle various aspects of the application, includeing rendering the poll page,
displaying the details of a specific poll, showing the results of a poll and
handling the users vote for a poll.

The views are decorated with @login_required which means the user needs to be authenticated
in order to use the polling application. If the user is not authenticated, they will be sent back
to the login page.

The detail view takes a question ID as a parameter and retrieves the corresponding question from the database.
If the question does not exist, a 404 error will be raised. The view then renders the html template
passing the question as context.

The `results` view is similar to the `detail` view. It retrieves the question based on the provided question ID,
raises a 404 error if the question does not exist, and renders the 'polls/results.html' template with the question
as context.

The `vote` view handles the user's vote for a specific question. It retrieves the question from the database using
the question ID. If the user has not selected a choice, or the choice does not exist, the view re-renders the 'polls/details.html'
template with an error message. If the choice is valid, the vote count for the choice is incremented, and the updated
choice is saved. Finally, the user is redirected to the 'polls:results' URL, which will display the results of the poll.

"""
from django.shortcuts import render
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .models import Choice, Question
from django.contrib.auth.decorators import login_required


# Create your views here.

@login_required(login_url='http://127.0.0.1:8000/user_auth/login/')
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, "polls/poll.html", context)

@login_required(login_url='http://127.0.0.1:8000/user_auth/login/')
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/details.html', {'question': question})

@login_required(login_url='http://127.0.0.1:8000/user_auth/login/')
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

@login_required(login_url='http://127.0.0.1:8000/user_auth/login/')
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice']
        )
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/details.html', {'question': question, 'error_message': "You didn't select a choice"})
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

polls/templates/polls/details.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Illusion</title>
  {% load static%}
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const scrollDownButton = document.querySelector(".scroll-down");
      scrollDownButton.addEventListener("click", function() {
        window.scrollBy({top: window.innerHeight, behavior: 'smooth' });
      });
    });
  </script>


  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  <!-- Custom CSS -->
  <style>

    @font-face {
      font-family: 'DEADLY KILLERS Regular';
      src: url('C:\Users\Beer C\Desktop\Hyperion Dev\Level 2\T23\illusion\homepage\templates\homepage\fonts\DeadlyKillers-K7RxX.ttf');
    }


    /* Set full height for header */
    #header {
      height: 100vh;
      background-size: cover;
      background-position: center center;
      position: relative;
    }

    /* Header carousel */
    #header .carousel-item {
      height: 100vh;
    }

    #header .carousel-item img {
      height: 100%;
      width: 100%;
      object-fit: cover;
    }

    /* Header text */
    #header-text {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      color: white;
      font-family: 'DEADLY KILLERS Regular';
      font-size: 3.5rem;
      text-align: center;
      z-index: 1;
    }

    /* Add padding for content below header */
    #content {
      padding-top: 100px;
    }

    /* Style the dropdown arrow icon */
    .scroll-down {
      display: block;
      position: absolute;
      bottom: 50px;
      left: 50%;
      margin-left: -20px;
      width: 40px;
      height: 40px;
      border-radius: 50%;
      /*background-color: #fff;*/
      text-align: center;
      line-height: 40px;
      font-size: 1.5rem;
      color: #fff;
      z-index: 2;
    }

    .scroll-down i {
      position: relative;
      top: 2px;
    }




    /* Custom styles for additional information */
    .info {
      background-color: #f2f2f2;
      padding: 50px;
      margin-bottom: 0px;
    }

    .info h2 {
      font-family: 'DEADLY KILLERS Regular', sans-serif;
      margin-bottom: 30px;
    }

    .info p {
      line-height: 1.5;
      font-family: 'Open Sans', sans-serif;
      margin-bottom: 20px;
    }

    /* Mobile styles */
    @media (max-width: 768px) {
      #header-text h1 {
        font-size: 4rem;
      }

      #header-text p {
        font-size: 1.5rem;
      }

      .info {
        padding: 20px;
      }

      /* Custom stylings for navbar */

      .navbar {
        background-color: white;
        font-family: 'Open Sans'; font-size:20px;
      }


     <!-- .navbar-toggler-icon::after {
        display: inline-block;
        margin-left: 0.3em;
        content: "";
        border-top: 0.3em solid;
        border-right: 0.3em solid transparent;
        border-left: 0.3em solid transparent;
        vertical-align: middle;
        }
      }

      /* Gradient overlay */

      .carousel-overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.8));
        z-index: 0;
      }

      btn.btn-primary {
        background-color: black;
      }

  </style>
</head>

<body>
 <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <div class="container">
      <a class="navbar-brand mr-auto" href="band-logo.png">
        <img src="{% static 'band-logo.png' %}" width="150" height="60" class="align-top-left" alt="band logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <i class="fas fa-angle-down"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:homepage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tourdates:tourdates' %}">Tour Dates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration:login' %}">Login</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!--Header -->
  <header id="header">
    <div id="header-carousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'tourdates-3.jpg' %}" alt="band header image" class="img-fluid">
        </div>
        <div class="carousel-item">
          <img src="{% static 'tourdates-1.jpg' %}" alt="band header image" class="img-fluid">
        </div>
        <div class="carousel-item">
          <img src="{% static 'contact-header-2.jpg' %}" alt="band header image" class="img-fluid">
        </div>
      </div>
    </div>
    <div class="carousel-overlay"></div>
    <div id="header-text">
      <h1>Poll</h1>
    </div>
  </header>

 <!-- Add dropdown arrow to header-->

  <a href="#info" class="scroll-down">
    <i class="fas fa-chevron-down"></i>
  </a>

  <!-- Content -->
<div class="info">
  <h2>Details</h2>
  <p>Please press back to answer the next poll question</p>
  <h1>{{ question.question_text }}</h1>

{% if error_message %}
<p class="error"><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}

  {% for choice in question.choice_set.all %}
  <div class="radio">
    <label>
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
      {{ choice.choice_text }}
    </label>
  </div>
  {% endfor %}

  <input type="submit" value="Vote" class="btn btn-primary" />
</form>

<!-- Bootstrap JS -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>

</html>

polls/templates/polls/poll.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Illusion</title>
  {% load static%}
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const scrollDownButton = document.querySelector(".scroll-down");
      scrollDownButton.addEventListener("click", function() {
        window.scrollBy({top: window.innerHeight, behavior: 'smooth' });
      });
    });
  </script>


  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  <!-- Custom CSS -->
  <style>

    @font-face {
      font-family: 'DEADLY KILLERS Regular';
      src: url('C:\Users\Beer C\Desktop\Hyperion Dev\Level 2\T23\illusion\homepage\templates\homepage\fonts\DeadlyKillers-K7RxX.ttf');
    }


    /* Set full height for header */
    #header {
      height: 100vh;
      background-size: cover;
      background-position: center center;
      position: relative;
    }

    /* Header carousel */
    #header .carousel-item {
      height: 100vh;
    }

    #header .carousel-item img {
      height: 100%;
      width: 100%;
      object-fit: cover;
    }

    /* Header text */
    #header-text {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      color: white;
      font-family: 'DEADLY KILLERS Regular';
      font-size: 3.5rem;
      text-align: center;
      z-index: 1;
    }

    /* Add padding for content below header */
    #content {
      padding-top: 100px;
    }

    /* Style the dropdown arrow icon */
    .scroll-down {
      display: block;
      position: absolute;
      bottom: 50px;
      left: 50%;
      margin-left: -20px;
      width: 40px;
      height: 40px;
      border-radius: 50%;
      /*background-color: #fff;*/
      text-align: center;
      line-height: 40px;
      font-size: 1.5rem;
      color: #fff;
      z-index: 2;
    }

    .scroll-down i {
      position: relative;
      top: 2px;
    }




    /* Custom styles for additional information */
    .info {
      background-color: #f2f2f2;
      padding: 50px;
      margin-bottom: 0px;
    }

    .info h2 {
      font-family: 'DEADLY KILLERS Regular', sans-serif;
      margin-bottom: 30px;
    }

    .info p {
      line-height: 1.5;
      font-family: 'Open Sans', sans-serif;
      margin-bottom: 20px;
    }

    /* Mobile styles */
    @media (max-width: 768px) {
      #header-text h1 {
        font-size: 4rem;
      }

      #header-text p {
        font-size: 1.5rem;
      }

      .info {
        padding: 20px;
      }

      /* Custom stylings for navbar */

      .navbar {
        background-color: white;
        font-family: 'Open Sans'; font-size:20px;
      }


     <!-- .navbar-toggler-icon::after {
        display: inline-block;
        margin-left: 0.3em;
        content: "";
        border-top: 0.3em solid;
        border-right: 0.3em solid transparent;
        border-left: 0.3em solid transparent;
        vertical-align: middle;
        }
      }

      /* Gradient overlay */

      .carousel-overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.8));
        z-index: 0;
      }

      .list-group-item {
        padding: 1rem;
        border-radius: 0;
        border-normal;
        max-width: 500px;
      }

      .list-group {
        background-color: #f8f9fa;
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 20px;
        margin-bottom: 20px;
      }
      
      .list-group {
        font-size: 1.5rem;
        margin-bottom: 15px;
      }
      
      .list-group input[type="radio"] {
        margin-right: 10px;
      }
      
      .list-group label {
        font-size: 1.2rem;
      }

      .text-center {
        margin-top: 2rem;
        padding: 1rem;
      }
      
      /* Adjust poll size and center it */
      .poll-container {
        width: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
      }

      .list-group-item {
        max-width: 100%;
      }

      .list-group label {
        display: block;
        width: 100%;
      }

      .list-group input[type="radio"] {
        margin-right: 10px;
      }

      .text-center {
        margin-top: 2rem;
        padding: 1rem;
      }

      .badge {
        background-color: #black;
        border-radius: 0.25rem;
        font-size: 1rem;
        font-weight: bold;
        }
    
      .text-center {
        margin-top: 2rem;
        padding: 1rem;
      }

      

  </style>
</head>

<body>
 <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
    <div class="container">
      <a class="navbar-brand mr-auto" href="band-logo.png">
        <img src="{% static 'band-logo.png' %}" width="150" height="60" class="align-top-left" alt="band logo">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        <i class="fas fa-angle-down"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'homepage:homepage' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tourdates:tourdates' %}">Tour Dates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'registration:login' %}">Login</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!--Header -->
  <header id="header">
    <div id="header-carousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'contact-header-3.jpg' %}" alt="band header image" class="img-fluid">
        </div>
        <div class="carousel-item">
          <img src="{% static 'contact-header.jpg' %}" alt="band header image" class="img-fluid">
        </div>
        <div class="carousel-item">
          <img src="{% static 'tourdates-2.jpg' %}" alt="band header image" class="img-fluid">
        </div>
      </div>
    </div>
    <div class="carousel-overlay"></div>
    <div id="header-text">
      <h1>Poll</h1>
      <p class="lead">Help Us Out By Answering Some Questions Below</p>
    </div>
  </header>

 <!-- Add dropdown arrow to header-->

  <a href="#info" class="scroll-down">
    <i class="fas fa-chevron-down"></i>
  </a>

  <!-- Content -->

<div class="info">
  <h2>Poll</h2>
  {% if user.is_authenticated %}
  {% if latest_question_list %}
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <ul class="list-group">
            {% for question in latest_question_list %}
            <li class="list-group-item d-flex, justify-content-between align-items-center">
              <a href="{% url 'polls:details' question.id %}" class="text-dark">{{ question.question_text }}</a>
              <span class="badge badge-primary badge-pill">{{ question.choice_set.count }}</span>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  {% endif %}
{% else %}
  <p>Please <a href="{% url 'login' %}">Login</a></p>
{% endif %}
</div>

<!-- Bootstrap JS -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</body>

</html>

polls/templates/polls/results.html
  <!DOCTYPE html>
  <html lang="en">
  
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Illusion</title>
    {% load static%}
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        const scrollDownButton = document.querySelector(".scroll-down");
        scrollDownButton.addEventListener("click", function() {
          window.scrollBy({top: window.innerHeight, behavior: 'smooth' });
        });
      });
    </script>
  
  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  
    <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  
    <!-- Custom CSS -->
    <style>
  
      @font-face {
        font-family: 'DEADLY KILLERS Regular';
        src: url('C:\Users\Beer C\Desktop\Hyperion Dev\Level 2\T23\illusion\homepage\templates\homepage\fonts\DeadlyKillers-K7RxX.ttf');
      }
  
  
      /* Set full height for header */
      #header {
        height: 100vh;
        background-size: cover;
        background-position: center center;
        position: relative;
      }
  
      /* Header carousel */
      #header .carousel-item {
        height: 100vh;
      }
  
      #header .carousel-item img {
        height: 100%;
        width: 100%;
        object-fit: cover;
      }
  
      /* Header text */
      #header-text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        color: white;
        font-family: 'DEADLY KILLERS Regular';
        font-size: 3.5rem;
        text-align: center;
        z-index: 1;
      }
  
      /* Add padding for content below header */
      #content {
        padding-top: 100px;
      }
  
      /* Style the dropdown arrow icon */
      .scroll-down {
        display: block;
        position: absolute;
        bottom: 50px;
        left: 50%;
        margin-left: -20px;
        width: 40px;
        height: 40px;
        border-radius: 50%;
        /*background-color: #fff;*/
        text-align: center;
        line-height: 40px;
        font-size: 1.5rem;
        color: #fff;
        z-index: 2;
      }
  
      .scroll-down i {
        position: relative;
        top: 2px;
      }
  
  
  
  
      /* Custom styles for additional information */
      .info {
        background-color: #f2f2f2;
        padding: 50px;
        margin-bottom: 0px;
      }
  
      .info h2 {
        font-family: 'DEADLY KILLERS Regular', sans-serif;
        margin-bottom: 30px;
      }
  
      .info p {
        line-height: 1.5;
        font-family: 'Open Sans', sans-serif;
        margin-bottom: 20px;
      }
  
      /* Mobile styles */
      @media (max-width: 768px) {
        #header-text h1 {
          font-size: 4rem;
        }
  
        #header-text p {
          font-size: 1.5rem;
        }
  
        .info {
          padding: 20px;
        }
  
        /* Custom stylings for navbar */
  
        .navbar {
          background-color: white;
          font-family: 'Open Sans'; font-size:20px;
        }
  
  
       <!-- .navbar-toggler-icon::after {
          display: inline-block;
          margin-left: 0.3em;
          content: "";
          border-top: 0.3em solid;
          border-right: 0.3em solid transparent;
          border-left: 0.3em solid transparent;
          vertical-align: middle;
          }
        }
  
        /* Gradient overlay */
  
        .carousel-overlay {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.8));
          z-index: 0;
        }
        
        btn.btn-primary {
          background-color: black;
        }
  
    </style>
  </head>
  
  <body>
   <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
      <div class="container">
        <a class="navbar-brand mr-auto" href="band-logo.png">
          <img src="{% static 'band-logo.png' %}" width="150" height="60" class="align-top-left" alt="band logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          <i class="fas fa-angle-down"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:homepage' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tourdates:tourdates' %}">Tour Dates</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'registration:login' %}">Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  
    <!--Header -->
    <header id="header">
      <div id="header-carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'header-image.jpg' %}" alt="band header image" class="img-fluid">
          </div>
          <div class="carousel-item">
            <img src="{% static 'header-image-3.jpg' %}" alt="band header image" class="img-fluid">
          </div>
          <div class="carousel-item">
            <img src="{% static 'tourdates-1.jpg' %}" alt="band header image" class="img-fluid">
          </div>
        </div>
      </div>
      <div class="carousel-overlay"></div>
      <div id="header-text">
        <h1>Poll</h1>
      </div>
    </header>
  
   <!-- Add dropdown arrow to header-->
  
    <a href="#info" class="scroll-down">
      <i class="fas fa-chevron-down"></i>
    </a>
  
    <!-- Content -->
    <div class='info'>
      <h2>Poll Results</h2>
      <p>Please press back two times to go back to the poll questions.</p>
      <div class="container mt-5">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <h1 class="mb-4">{{ question.question_text }}</h1>
            <ul class="list-group">
              {% for choice in question.choice_set.all %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ choice.choice_text }}
                <span class="badge badge-primary badge-pill">{{ choice.votes }}</span>
              </li>
              {% endfor %}
            </ul>
            <a href="{% url 'polls:details' question.id %}" class="btn btn-primary mt-4">Vote again?</a>
          </div>
        </div>
      </div>
    </div>
  
  <!-- Bootstrap JS -->
  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  
  </body>
  
  </html>